name: Terraform Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        directory:
          - modules/azure-vm-network
          - modules/aws-vm-network
          - modules/azure-file-storage
          - modules/aws-s3-storage
          - examples/azure-vm
          - examples/aws-vm
          - examples/azure-storage
          - examples/aws-storage
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Format Check
        working-directory: ${{ matrix.directory }}
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: ${{ matrix.directory }}
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: ${{ matrix.directory }}
        run: terraform validate
